services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.production.local
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80
    env_file:
      - .env
      - .env.production.local
